### PR TITLE
Issue 233: Fix Flink samples build

### LINKED ISSUE #233: Flink Samples do not work in Pravega 0.6
**Problem description**
I was going to execute the Flink wordcount sample, and it turns out that the compiled wordcount reader and writer are crashing:
```
pravega-samples/flink-connector-examples/build/install/pravega-flink-examples$ bin/wordCountWriter
Exception in thread "main" java.lang.NoSuchMethodError: io.pravega.shared.controller.tracing.RPCTracingHelpers.getClientInterceptor()Lio/grpc/ClientInterceptor;
	at io.pravega.client.stream.impl.ControllerImpl.<init>(ControllerImpl.java:183)
	at io.pravega.client.stream.impl.ControllerImpl.<init>(ControllerImpl.java:142)
	at io.pravega.client.admin.impl.StreamManagerImpl.<init>(StreamManagerImpl.java:49)
	at io.pravega.client.admin.StreamManager.create(StreamManager.java:42)
	at io.pravega.example.flink.Utils.createStream(Utils.java:41)
	at io.pravega.example.flink.Utils.createStream(Utils.java:27)
	at io.pravega.example.flink.wordcount.WordCountWriter.main(WordCountWriter.java:62)
```
Looks like the library used is wrong in the Flink connector, given that the regular Pravega samples work well.

**Problem location**
Flink connector from 0.6.0 to 0.6.2.

**Suggestions for an improvement**
Fix why the Flink connector cannot be used after regular compilation.

### PR DESCRIPTION
**Pull request by RaulGracia**
**Change log description**
Removes the Pravega client from Flink build dependencies.

**Purpose of the change**
Fixes #233.

**What the code does**
According to @crazyzhou, 
>This bug is caused by the relocation of the io.grpc package. The return structure of the getClientInterceptor in flink connector is changed to io.pravega.shaded.io.grpc rather than io.grpc, causing the io.grpc return method not exist. See:
https://github.com/pravega/flink-connectors/blob/master/build.gradle#L157
It's a behaviour from the first commit of the repository. It was meant to shade the common libraries which could cause potential version conflicts with Flink.
My suggestion is to delete the pravega client dependency in the samples. See:
https://github.com/pravega/pravega-samples/blob/master/flink-connector-examples/build.gradle#L27
Tested in my environment that it's working fine. And we may also tell the users not to include both the connector and the client dependencies in the same project. This may cause conflicts like this

This PR just removes the Pravega client library from the Flink build to avoid the GPRC dependency conflict.

**How to verify it**
The build works and now the conflict has been removed.

### CODE REVIEW

**Comment by RaulGracia** [comment]
This should be cherry picked to 0.6 branch.
